# Generated by Django 5.0b1 on 2023-11-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='products')),
                ('image_1', models.ImageField(upload_to='uploads/images')),
                ('image_2', models.ImageField(upload_to='uploads/images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('top_selling', models.BooleanField(default=False)),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory')),
            ],
        ),
    ]
