# Generated by Django 4.2.6 on 2023-11-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='products')),
                ('image_1', models.FileField(upload_to='products')),
                ('image_2', models.FileField(upload_to='products')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('top_selling', models.BooleanField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product-categories')),
            ],
        ),
    ]
