# Generated by Django 4.2.6 on 2023-11-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.FileField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.FileField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False),
        ),
    ]
